### ISSUE TITLE
Delete top navigation.

### ISSUE THREAD

**Issue by ebompais-pham** [Klap-in/dokuwiki-plugin-docnavigation#10]
Hi!

I love that extension. It is essential for readers to understand how to navigate logically between pages. 

But I have a problem. In my wiki, top navigation is a problem. Readers could go to the next page before reading the current one. So, I'd like to delete it. How can I do that?

I thank you very much in advance. 

Cordially,

Etienne.

**Comment by Klap-in** [comment]
You could modify the code manually (but that is not persistent at plugin update of course):

https://github.com/Klap-in/dokuwiki-plugin-docnavigation/blob/f63aba6b435ec5ecb6154ce430aade60e4623020/action.php#L39-L41
If you remove `$this->getNavbar($linktoToC = false)
                        . ` then the part at the top of the page is not displayed.

**Comment by ebompais-pham** [comment]
It works perfectly ! I'll note to delete that code after a plugin update. Thank you very much for your help!
