### ISSUE TITLE
Compatibility issue with plugin ckgedit

### ISSUE THREAD

**Issue by Nicolas-Git-13** [Klap-in/dokuwiki-plugin-docnavigation#13]
This is not possible to have this pagination working with ckgedit plugin : The ckgedit Automatically change -> to →. 

This issue can be solved keeping backward compatibility by adding after the **line 66 of syntax/pagenav.php** the line :

`$this->Lexer->addSpecialPattern('<-[^\n]*\^[^\n]*\^[^\n]*>>', $mode, 'plugin_docnavigation_pagenav');`

**Comment by Nicolas-Git-13** [comment]
Can you do a pull request to do this change ?

Thank you.

**Comment by Klap-in** [comment]
The issue is solved?

**Comment by Nicolas-Git-13** [comment]
I have supplyed a pull request instead

Le ven. 26 juil. 2019 à 00:08, Gerrit Uitslag <notifications@github.com> a
écrit :
