### ISSUE TITLE
Interaction with ckgedit

### ISSUE THREAD

**Issue by lostwatt** [Klap-in/dokuwiki-plugin-docnavigation#18]
When opening a page using docnavigation markup in ckgedit for editing, the syntax is incorrectly changed so that resaving the page that has been opened without making any edits will now disable the intended docnavigation markup.

The change occurs at the right end where "->" should appear in edit mode. In ckgedit in edit mode the right end characters come back as → (which is the way they are supposed to appear on the page in view mode). So these characters have to be corrected before saving the page again or the navigation markings will no longer work.

**Comment by Klap-in** [comment]
In #14 an alternative syntax is proposed.
Please use that one if you use ckgedit.
`<< namespace:previous_page ^ namespace:startpage ^ namespace:next page >>`
