### ISSUE TITLE
Use of anchor breaks link

### ISSUE THREAD

**Issue by tangotribe** [Klap-in/dokuwiki-plugin-docnavigation#19]
<-ns:prev-page-link:previousLabel^ns:start-or-chapter-link#anchor^ns:next-page-link:nextLabel->
In the command line above, the # character is taken as a break that starts the label. This means that we can't include anchors in our links.

**Comment by Klap-in** [comment]
It is not used as break that starts the label. It is just ignore, on purpose, because I need the full pageid without hash. I will reapply them.
