### ISSUE TITLE
How to specify a root-level link?

### ISSUE THREAD

**Issue by tangotribe** [Klap-in/dokuwiki-plugin-docnavigation#20]
Example: in go:map we have <- Start ^ :top|Map of Step 1 ^ go2:map2|Map of Step 2 ->

We want the first, "previous" link to reference the Start page *at the root*. The second one, with just a colon assumes the current namespace, as expected. The third, "Next" link with an explicit namespace name also works as expected.

So, how can we specify a link at the root level?

**Comment by iandavo2** [comment]
I also have this request. The plugin does not action a link to the root namespace.

**Comment by Klap-in** [comment]
The logic at https://www.dokuwiki.org/namespaces should be followed..

So: `:Start` (or `:` in most cases) should be the start page in root
While `start`, `.start` and `.:start` are all start pages in current namespace

I found that in the code the pageids were resolved twice. So first from : to start, resolving again results in `currentns:start`, I will fix this. Thanks for reporting!
