### ISSUE TITLE
Error Message "<doctoc>: page A don't link back to B. ", even though it does!

### ISSUE THREAD

**Issue by Chris75forumname** [Klap-in/dokuwiki-plugin-docnavigation#21]
Thank you very much for this plugin!!!
I am implementing an calendar in dokuwiki (its a pitty that I have to) from scratch.
On the start page I get the Error Message "<doctoc>: page A don't link back to B. ", even though it does! And I can use the links back and forth fine! I find such checks and messages very helpful! But how can I suppress the error messages after I made sure everything actually works as it should?
Thanks! Chris

**Comment by Klap-in** [comment]
That means that this check, has false positives. I prefer not to suppress this check.
https://github.com/Klap-in/dokuwiki-plugin-docnavigation/blob/8c28406dbb88a3408b12059e8d44cc4227ab7583/syntax/toc.php#L224-L231

 Could you provide an small example of a case that reproduce this? Which `<doctoc>` and `<- ^^->` should I use to reproduce it?

I do not expect it is a caching issue, but that is easy to check by just saving the Configuration Manager again and next reload the page.

**Comment by Klap-in** [comment]
Please could you provide which syntaxes you did use on the page with `<doctoc>` and on the first page?

**Comment by Klap-in** [comment]
I assume it is the same issue as the Bug 3 in #22. 

That one is solved by only checking link backs between the page navigation syntaxes, and not between the doctoc and the page navigation syntax. It is fine to refer there, but not required. Therefore, that case does not need a check.
