### ISSUE TITLE
Investigate incompatibility with Igor

### ISSUE THREAD

**Issue by Klap-in** [Klap-in/dokuwiki-plugin-docnavigation#22]
In the wiki it is marked incompatible with latest version (Igor).
@desbest do you have feedback where to look for?

**Comment by Klap-in** [comment]
I assume that recent php8 improvements should fix this.

**Comment by desbest** [comment]
Sorry for the late reply. I was fixing my laptop.

1. Entering `<doctoc>` as page markup on its own, doesn't work. When I enter it in, nothing happens.
2. The `hidepagelink` parameter of `<doctoc>` is not respected. It doesn't do anything.

**Comment by Klap-in** [comment]
`hidepagelink` is a new addition. You have installed the latest version of this plugin?

What do you mean wih 'nothing happens'. That the `<doctoc>` is even still in the text? Or is the syntax recognized, but do you see nothing in the text? If you include `<doctoc>` without other references, then you will get one link to the page self where the syntax was placed.

**Comment by desbest** [comment]
Sorry for the late reply again. I was fixing my laptop. Here's more clarification about the 3 issues with the Igor version.

# Bug 1
Names of bookmarks don't show, when the previous and next pages are defined

```
<-testbook:chapter-one^testbook:home^testbook:chapter-three->
```

![docnavigation bug with dokuwiki igor version 1](https://user-images.githubusercontent.com/1139316/213896076-d07abb08-d94f-4a81-9e80-b342945745a4.png)

# Bug 2

Error when the <doctoc> output says I haven't linked back to a page, when I have linked to it, from the footer navigation links

```
<-testbook:chapter-one^testbook:home^testbook:chapter-two->
```

![docnavigation bug with dokuwiki igor version 2 merged](https://user-images.githubusercontent.com/1139316/213896623-6158f6a4-6907-4025-a909-d11779d78754.png)

# Bug 3 and 4

3. Error when the `<doctoc>` output says I haven't linked back to a page, when actually I have, along with another bug 
4. When the `<doctoc>` syntax fails to generate the table of contents from the current page it's being mentioned on, within the absence of any parameters

```
**Added link for testing:** [[testbook:home]]
```

```
<doctoc>
```

# False alert
<-testbook:chapter-one^testbook:home^testbook:chapter-three->

**Comment by Klap-in** [comment]
Thanks for providing more info, that helps!

Bug 1: solved by 041de83.  I did not test with `useheading` settings disabled when cleaning up the code, so I didn't catch this one.
Bug 2: could you share the syntax you used for the `<doctoc>` as well? Is this the same bug as Bug 3?
Bug 3: This belongs to the yellowgreen image? I made the assumption in the code that the first page has to refer with `<-...^` to the page with the `<doctoc>`. But indeed this is not logic to do always, it is only logic when that page with `<doctoc>` is also referring with page navigation syntax to the 'first page'. Fixed in 5957890
Bug 4: `<doctoc>` does not need start-parameter if there is page navigation syntax (`<-...^...^...->`) on the same page.
If there is no page navigation syntax on the page with `<doctoc>` you must use the start=ns:firstpage, in your case `<doctoc start=testbook:chapter-one>`. So this is not a bug. 
Do I understand correctly that you assumed that because the page navigation syntax on another page has a reference to the home page with the `<doctoc>`, the `<doctoc>` on that homepage should know already where its first page is? This works if you have one first page referring to that home page with doctoc. If you have two sets of pages and therefore two `<doctoc>` on the home page, it is ambivalent which reference it should pick as first page. Therefore I choice to use the start parameter if the page navigation syntax is not on the page with `<doctoc>`.
Bug 5: ok.

**Comment by desbest** [comment]
# Bug 2

**testbook:home** 
```
<doctoc start= testbook:chapter-one, hidepagelink=0>
```

**testbook:chapter-one**
```
====== Chapter One ======

<doctoc>

**Added link for testing:** [[testbook:home]]
```

# Bug 3

**testbook:home**
```
<doctoc start= testbook:chapter-one, hidepagelink=0>
```

**testbook:chapter-one**
```
====== Chapter One ======

<doctoc>

**Added link for testing:** [[testbook:home]]
```

# The difference between bug 2 and bug 4

To clarify, bug 4 occurs in the absence of a `<doctoc>` appearing on the contents page. Therefore meaning, that the error only appears once on the entire website. For bug 4, we are only looking of the presence of the page in question being looked for, that `<doctoc>` throws an error for, within the same page that the user is currently visiting. There is no scanning for any wiki pages, that the user isn't currently on.

**chapter:one**
```
====== Chapter One ======

**Added link for testing:** [[testbook:home]]

<doctoc start= testbook:chapter-one, hidepagelink=0>

<-testbook:chapter-one^testbook:home^->
```


Another important difference to remember is this

| &#10065;&#10065;&#10065;&#10065;&#10065;  | Bug 2 | Bug 3 | Bug 4|
| ------------- | ------------- | ---------- | -----| 
| **Problematic formatting tag**  | `<prevpage-^indexpage^-nextpage>`  | `<doctoc>` | `<doctoc>` |
| **Blank pages needed to edit, in order to trigger the bug**  | 2   | 2  |  1 | 

To avoid further confusing things, I'll answer your other questions about bug 4, once you've made some progress from the new information above.

**Comment by Klap-in** [comment]
So far I cannot grab what is going on, I will do some testing later to try it out.
Did you see that I made an update? Does it improve the situation already?

**Comment by desbest** [comment]
I've just upgraded to the latest version now. **2023-01-23**

- **Bug 1:** fixed
- **Bug 2:** fixed
- **Bug 3:** fixed
- **Bug 4:** fixed
- **Supposed Bug 5:** N/A

Thank you for your help.

**Comment by Klap-in** [comment]
ok, great. Thanks for reporting!
