### ISSUE TITLE
PHP error when linking to non-existing page

### ISSUE THREAD

**Issue by rvaandrager** [Klap-in/dokuwiki-plugin-docnavigation#25]
When creating links to non-existing pages in a navigation bar, the following PHP error occurs:

`Warning: Undefined array key "rawtitle" in /volume1/webapps/dokuwiki/lib/plugins/docnavigation/action.php on line 121`

Example dokuwiki text:
`<- namespace:previous_page ^ namespace:startpage ^ namespace:next page ->`

If `namespace:previous_page` does not exist, the error is shown.

Dokuwiki version Igor is used, with the most recent version updated 2022-10-06.

**Comment by Klap-in** [comment]
Sorry, I forgot to test again with useheading off after refactoring. Fixed by 041de83
