### ISSUE TITLE
E_WARNING: Undefined array key "start" /dokuwiki-test2/lib/plugins/docnavigation/action.php(58)

### ISSUE THREAD

**Issue by fiwswe** [Klap-in/dokuwiki-plugin-docnavigation#30]
DokuWiki 2023-04-04a "Jack Jackrum"
PHP 8.2.6 (via PHP-FPM)
DocNavigation Plugin 2023-01-23

This happens when editing a section on the `id=start` page and pressing the _Preview_ button. Note that I am not using the DocNavigation Plugin on this page at all.

My suggestion would be to change:
https://github.com/Klap-in/dokuwiki-plugin-docnavigation/blob/b8f9374965b32520d701107d802cfc057f7de187/action.php#L57
to
```php
            if ($pagenav && array_key_exists($ID, $pagenav->data)) {
```

But I don't know if that is just a band aid or a real fix.

**Comment by Klap-in** [comment]
Thanks for reporting!
